### ISSUE TITLE
 Error accessing project webpage with iOS: "ReferenceError: Can't find variable: OffscreenCanvas"

### ISSUE THREAD

**Issue by CraxGrix** [852Kerfunkle/threads-es#1]
Hi there,

I'm reaching out to report an issue I encountered while trying to access a project webpage that uses the 'threads-es' library on my iOS device. When attempting to load the page, I received the following error message:

"ReferenceError: Can't find variable: OffscreenCanvas"

I am running iOS version **16.1.1**. I have tried accessing the page on multiple occasions with the same result.

Could you please advise on what steps I can take to resolve this issue or provide more information about the cause of the error?

Thank you for your time and assistance.

**Comment by 852Kerfunkle** [comment]
Hi!

Thank you for letting me know.

I suppose it's the check for Transferable objects here: https://github.com/852Kerfunkle/threads-es/blob/b29facbbb21a5461b73c4d30b1bed669b12c8f53/src/shared/TransferDescriptor.ts#L14 (and following).

It's not strictly required (types should be checked). I'll have a look if it makes sense to remove it.

**Comment by 852Kerfunkle** [comment]
I'll make a 0.3.1 release shortly :)
