### ISSUE TITLE
Uncaught (in promise) Error: Failed to spawn thread pool. Errors: Thread #0: Error: crypto.getRandomUID() is undefined

### ISSUE THREAD

**Issue by CraxGrix** [852Kerfunkle/threads-es#2]
I encountered an issue while using the library on a non-https website. The error message is 

```
Uncaught (in promise) Error: Failed to spawn thread pool. 
Errors: Thread #0: Error: crypto.getRandomUID() is undefined
```
From my initial investigation, this error might be caused by the inability to call 'crypto.getRandomUID' in a non-https environment.

Could you please advise on what steps I can take to resolve this issue or provide more information about the cause of the error?

Thank you for your time and assistance.

**Comment by 852Kerfunkle** [comment]
Heya.

Yup, `crypto.getRandomUID` is only available in secure contexts. I wondered if I should put this in the readme.

Non-http simply wasn't a requirement for me (and localhost is also considered a secure context in most browsers).

I can probably add another way to generate UIDs. Worse case, there's always `nanoid`, for example (rip "zero-dependency").

Maybe there's a way to add it as a peer dependency and use it if available and the context isn't secure. Would that work for you?

**Comment by CraxGrix** [comment]
> Heya.
> 
> Yup, `crypto.getRandomUID` is only available in secure contexts. I wondered if I should put this in the readme.
> 
> Non-http simply wasn't a requirement for me (and localhost is also considered a secure context in most browsers).
> 
> I can probably add another way to generate UIDs. Worse case, there's always `nanoid`, for example (rip "zero-dependency").
> 
> Maybe there's a way to add it as a peer dependency and use it if available and the context isn't secure. Would that work for you?

Perhaps another way to generate UID can be added, which is called when "crypto.getRandomUID" is not available, instead of throwing an exception. What do you think of this approach?

**Comment by 852Kerfunkle** [comment]
> Perhaps another way to generate UID can be added, which is called when "crypto.getRandomUID" is not available, instead of throwing an exception. What do you think of this approach?

Yes, I suggested nanoid (https://github.com/ai/nanoid) as a peer dependency - or maybe I'll just add something like this part here, to stay with the "zero-dependency" ( :) ): https://github.com/ai/nanoid/blob/46d7cab0b2632a9dbee9028a96c9878b9d951f42/non-secure/index.js#L23

**Comment by CraxGrix** [comment]
> > Perhaps another way to generate UID can be added, which is called when "crypto.getRandomUID" is not available, instead of throwing an exception. What do you think of this approach?
> 
> Yes, I suggested nanoid (https://github.com/ai/nanoid) as a peer dependency - or maybe I'll just add something like this part here, to stay with the "zero-dependency" ( :) ): https://github.com/ai/nanoid/blob/46d7cab0b2632a9dbee9028a96c9878b9d951f42/non-secure/index.js#L23

I think this solution is very good

**Comment by 852Kerfunkle** [comment]
I've made a 0.3.2 release.

Thank you for the feedback.
